add touch bar tokens mac
momentum-design/tokens pull request #225
Opened 2022-06-22 12:47 UTC by NotNestor

Add colour tokens for touch bar on mac

https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=15991%3A144836

<img width="408" alt="Screenshot 2022-06-22 at 13 46 20" src="https://user-images.githubusercontent.com/87858909/175032450-44048f56-84cc-4423-80b5-f5188a68ae1f.png">

2022-06-22 13:20 UTC, NotNestor commented
theme tokens need to be defined for the core tokens before this PR can be progressed

2022-07-01 10:55 UTC, nataliadelmar requested changes
looks good to me. Just a typo and that's it

2022-07-01 10:55 UTC, nataliadelmar commented on platformcomponents/desktop/touchbar.json
> +      "encCall": "@theme-common-touchbar-background-red",
should it be endCall?

2022-07-01 10:55 UTC, nataliadelmar commented on theme-data/win-system-hc/win-system-hc-common.json
> +      }
did you add this space in purpose? if not, please delete :)

2022-07-01 10:57 UTC, NotNestor commented on platformcomponents/desktop/touchbar.json
> +      "encCall": "@theme-common-touchbar-background-red",
👍

2022-07-01 11:25 UTC, merged