Adding partner colours (word, pdf, onenote, etc) for file content attachments
momentum-design/tokens pull request #280
Opened 2023-01-11 15:04 UTC by leonardjoe

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

Adding new tokens to support "partner" colours for file bricklet attachments (word, excel, PDF, etc).

* [Readme](https://github.com/momentum-design/tokens/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/tokens/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/tokens/blob/master/CONTRIBUTING.md)

# Description

https://www.figma.com/file/n9T5usku57ecvPArT9SpWO/Tokens---Core-Color?node-id=3906%3A2&t=ZYuvVMkkHBjPHmSI-0
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=2547%3A0&t=oJe9sbjQooTxKrJG-0

<img width="581" alt="Screenshot 2023-01-11 at 15 03 15" src="https://user-images.githubusercontent.com/44676517/211840360-5afe1378-3830-4ce8-9237-3573dc92197d.png">
<img width="459" alt="Screenshot 2023-01-11 at 15 04 35" src="https://user-images.githubusercontent.com/44676517/211840648-f837619f-7379-4d35-b0df-a61ffaf1a91d.png">

# Links

*Links to relevent resources.*

2023-01-11 15:07 UTC, leonardjoe commented on core/color/partners.json
> +{
these are the colours required, as defined here: https://www.figma.com/file/n9T5usku57ecvPArT9SpWO/Tokens---Core-Color?node-id=3906%3A2&t=ZYuvVMkkHBjPHmSI-0

2023-01-11 15:08 UTC, leonardjoe commented on platformcomponents/desktop/attachment-file-branded.json
> +  "attachment-file-branded": {
I based this on the existing ```attachment-file-default.json``` which covers the "default" (non-partner) files

2023-01-11 15:09 UTC, leonardjoe commented on theme-data/win-system-hc/win-system-hc-common.json
> +      "content": {
not sure if this is the correct thing to do, but the script (```npm run build:windows```) gave me errors until I added this definition in here also

2023-01-11 15:35 UTC, NotNestor approved these changes

2023-01-12 14:42 UTC, nataliadelmar requested changes

2023-01-12 14:42 UTC, nataliadelmar commented on platformcomponents/desktop/attachment-file-branded.json
> +        "background-pdf": "@theme-common-content-content-pdf",
let's do a parent for background that has pdf, word, etc.. inside

2023-01-12 14:42 UTC, nataliadelmar commented on theme-data/common/common.json
> +        "content-pdf": "@color-partner-pdf",
let's not repeat 'content' in the key name of lines 137 - 145

2023-01-12 14:42 UTC, nataliadelmar commented on theme-data/win-system-hc/win-system-hc-common.json
> +        "content-pdf": "@color-partner-pdf",
You get the values from here. In this case, all content colors would be @color-hc-SystemColorHighlightColor

"pdf": "@color-hc-SystemColorHighlightColor"
"word": "@color-hc-SystemColorHighlightColor"
"powerpoint": "@color-hc-SystemColorHighlightColor"
...
"keynote": "@color-hc-SystemColorHighlightColor"

2023-01-12 15:26 UTC, nataliadelmar approved these changes

2023-01-12 15:26 UTC, merged