added ios toolbar button tokens
momentum-design/tokens pull request #82
Opened 2021-09-02 23:17 UTC by JuliaCassella

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*

Added tokens toolbarButton iOS specific component. [figma](https://www.figma.com/file/L67wWWZaXcvVOLEpn77adE/Components---iOS?node-id=6583%3A66671)
* [Readme](https://github.com/momentum-design/tokens/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/tokens/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/tokens/blob/master/CONTRIBUTING.md)

# Description

*The full description of the changes made in this request.*

# Links

*Links to relevent resources.*

2021-09-02 23:19 UTC, brunnerjosh approved these changes

2021-09-06 10:43 UTC, paulwitty requested changes

2021-09-06 10:43 UTC, paulwitty commented on platformcomponents/ios/toolbarButton.json
> +            "background": "@theme-globaltint-pressed"",
There's an extra " at the end of this line. Please make sure you try building the tokens before submitting the PR.

2021-09-08 09:03 UTC, paulwitty approved these changes

2021-09-08 09:03 UTC, merged